resources:
  - name: gitResource
    type: GitRepo
    configuration:
      path: lidorv/guy
      gitProvider: VCS_4
      buildOn:
        pullRequestCreate: true
      branches:
        include: master
  - name: build-info-resource
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory_4
      buildName: BUILD-A
      buildNumber: $run_number
pipelines:
  - name: Pipeline-1
    configuration:
      environmentVariables:
        readOnly:
          CI: "true"
          JFROG_CLI_BUILD_NAME: BUILD-A
          JFROG_CLI_BUILD_NUMBER: $run_number
          JFROG_CLI_BUILD_URL: $step_url
    steps:
      - name: Build
        type: GradleBuild
        configuration:
          gradleCommand: artifactoryPublish
          resolverRepo: bbb-gradle-dev
          deployerRepo: bbb-gradle-dev
          useWrapper: "true"
          environmentVariables:
            JFROG_BUILD_STATUS: PASS
          integrations:
            - name: Artifactory_4
          inputResources:
            - name: gitResource
        execution:
          onFailure:
            - export JFROG_BUILD_STATUS=FAIL
            - jfrog rt bce
            - jfrog rt bag
            - jfrog rt bp
      - name: PublishBuildInfoStep
        type: PublishBuildInfo
        configuration:
          inputResources:
            - name: gitResource
          outputResources:
            - name: build-info-resource
          inputSteps:
            - name: Build
          forceXrayScan: true
        execution:
          onComplete:
            - update_commit_status gitResource
